<?= $this->doctype() ?>
<html lang="hu">
<head>
	<title><?= $this->globalConfig('website_name'); ?></title>
	<?= $this->headMeta()
		->appendName('viewport', 'initial-scale=1')
		->appendName('charset', 'utf-8')
		->prependCharset('utf-8')
	?>

	<?= $this->headLink()
		->appendStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,500,700,400italic')
		->appendStylesheet('/bower_components/angular-material/angular-material.css')
		->appendStylesheet('/bower_components/material-calendar/dist/angular-material-calendar.min.css')
		->appendStylesheet('/css/style.css')
	?>

	<?= $this->headScript()
		->prependFile("/js/dragresize.js")
		->prependFile("/js/calendar/Controller.js")
		->prependFile('/js/calendar/directive.js')
		->prependFile('/js/application/Controller.js')
			->prependFile('/js/application/directive.js')
		->prependFile('/js/application/app.js')
		->prependFile('/bower_components/jquery/dist/jquery.min.js')
		->prependFile('/bower_components/angular-animate/angular-animate.js')
		->prependFile('/bower_components/angular-aria/angular-aria.js')
		->prependFile('/bower_components/material-calendar/dist/angular-material-calendar.min.js')
		->prependFile('/bower_components/angular-material/angular-material.js')
		->prependFile('/bower_components/angular-material-icons/angular-material-icons.js')
		->prependFile('/bower_components/angular-sanitize/angular-sanitize.js')
		->prependFile('/bower_components/angular/angular.js')
	?>
</head>
<body ng-app="eDev" layout="column" ng-controller="Application">
<md-progress-linear md-mode="indeterminate" style="margin-bottom: -5px !important; float: left; z-index: 100; " ng-show="isLoading"></md-progress-linear>
<md-toolbar layout="row">
	<div class="md-toolbar-tools">
		<md-button ng-click="toggleSidenav('left')" hide-gt-sm class="md-icon-button">
			<md-icon aria-label="Menu" md-svg-icon="/menu.svg">
			</md-icon>
		</md-button>
		<h1><?= (isset($this->moduleName) ? $this->moduleName : $this->globalConfig('website_name')) ?></h1>
	</div>
</md-toolbar>
<div layout="row" flex>
	<md-sidenav layout="column" class="md-sidenav-left md-whiteframe-4dp" md-component-id="left"
				md-is-locked-open="$mdMedia('gt-sm')">
		<md-toolbar class="md-tall md-hue-2 md-default-theme">
			<div layout="column" class="md-toolbar-tools-bottom inset profile-section">
				<span class="picture">
					<svg class="user-avatar" viewBox="0 0 128 128" height="64" width="64" pointer-events="none">
						<path fill="#FF8A80" d="M0 0h128v128H0z"></path>
						<path fill="#FFE0B2"
							  d="M36.3 94.8c6.4 7.3 16.2 12.1 27.3 12.4 10.7-.3 20.3-4.7 26.7-11.6l.2.1c-17-13.3-12.9-23.4-8.5-28.6 1.3-1.2 2.8-2.5 4.4-3.9l13.1-11c1.5-1.2 2.6-3 2.9-5.1.6-4.4-2.5-8.4-6.9-9.1-1.5-.2-3 0-4.3.6-.3-1.3-.4-2.7-1.6-3.5-1.4-.9-2.8-1.7-4.2-2.5-7.1-3.9-14.9-6.6-23-7.9-5.4-.9-11-1.2-16.1.7-3.3 1.2-6.1 3.2-8.7 5.6-1.3 1.2-2.5 2.4-3.7 3.7l-1.8 1.9c-.3.3-.5.6-.8.8-.1.1-.2 0-.4.2.1.2.1.5.1.6-1-.3-2.1-.4-3.2-.2-4.4.6-7.5 4.7-6.9 9.1.3 2.1 1.3 3.8 2.8 5.1l11 9.3c1.8 1.5 3.3 3.8 4.6 5.7 1.5 2.3 2.8 4.9 3.5 7.6 1.7 6.8-.8 13.4-5.4 18.4-.5.6-1.1 1-1.4 1.7-.2.6-.4 1.3-.6 2-.4 1.5-.5 3.1-.3 4.6.4 3.1 1.8 6.1 4.1 8.2 3.3 3 8 4 12.4 4.5 5.2.6 10.5.7 15.7.2 4.5-.4 9.1-1.2 13-3.4 5.6-3.1 9.6-8.9 10.5-15.2M76.4 46c.9 0 1.6.7 1.6 1.6 0 .9-.7 1.6-1.6 1.6-.9 0-1.6-.7-1.6-1.6-.1-.9.7-1.6 1.6-1.6zm-25.7 0c.9 0 1.6.7 1.6 1.6 0 .9-.7 1.6-1.6 1.6-.9 0-1.6-.7-1.6-1.6-.1-.9.7-1.6 1.6-1.6z"></path>
						<path fill="#E0F7FA"
							  d="M105.3 106.1c-.9-1.3-1.3-1.9-1.3-1.9l-.2-.3c-.6-.9-1.2-1.7-1.9-2.4-3.2-3.5-7.3-5.4-11.4-5.7 0 0 .1 0 .1.1l-.2-.1c-6.4 6.9-16 11.3-26.7 11.6-11.2-.3-21.1-5.1-27.5-12.6-.1.2-.2.4-.2.5-3.1.9-6 2.7-8.4 5.4l-.2.2s-.5.6-1.5 1.7c-.9 1.1-2.2 2.6-3.7 4.5-3.1 3.9-7.2 9.5-11.7 16.6-.9 1.4-1.7 2.8-2.6 4.3h109.6c-3.4-7.1-6.5-12.8-8.9-16.9-1.5-2.2-2.6-3.8-3.3-5z"></path>
						<circle fill="#444" cx="76.3" cy="47.5" r="2"></circle>
						<circle fill="#444" cx="50.7" cy="47.6" r="2"></circle>
						<path fill="#444"
							  d="M48.1 27.4c4.5 5.9 15.5 12.1 42.4 8.4-2.2-6.9-6.8-12.6-12.6-16.4C95.1 20.9 92 10 92 10c-1.4 5.5-11.1 4.4-11.1 4.4H62.1c-1.7-.1-3.4 0-5.2.3-12.8 1.8-22.6 11.1-25.7 22.9 10.6-1.9 15.3-7.6 16.9-10.2z"></path>
					</svg>
				</span>
				<span class="basic-info">
					<div>Firstname Lastname</div>
					<div>email@domainname.com</div>
				</span>

			</div>
		</md-toolbar>
		<md-button ng-repeat="item in menu">
			<a ng-click="toRoute(item)">
				<md-item-content md-ink-ripple layout="row" layout-align="start center"
								 ng-class="{'child-menu':item.inset}">
					<div class="inset">
						<ng-md-icon style="height: 100% !important;" icon="{{item.icon}}"></ng-md-icon>
					</div>
					<div class="inset">{{item.title}}
					</div>
				</md-item-content>
			</a>
		</md-button>
	</md-sidenav>
	<div layout="column" flex id="content">
		<md-content layout="column" flex class="md-padding">
			<eval-async><?= $this->content ?></eval-async>
		</md-content>
	</div>
</div>
</body>
</html>
