routes:
  calendar_data:
    route: '/calendarrest/:action[/]'
    controller: "calendarRest"
    constraint:
      action: "(\\w+)"
    default:
          action: "getdata"

invokable:
  calendar: "Calendar\\Controller\\CalendarController"
  calendarRest: "Calendar\\Controller\\CalendarRest"

view:
  calendar/container: "Calendar/view/container.phtml"
  calendar/export: "Calendar/view/export.phtml"
  calendar/settings: "Calendar/view/settings.phtml"
