website_name: "eDev (pre-alpha)"

Modules:
  - Application
  - Calendar
debug: true
error_page_controller: "decoy\\base\\ErrorController"

use_database: true
Database:
  driver: pdo_mysql
  host: localhost
  user: root
  charset: "utf8"
  password:
  dbname: edev