<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CalenradEntryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalenradEntryTypeRepository extends EntityRepository
{
}
