<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectUserMapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUserMapRepository extends EntityRepository
{
}
