<!--https://angular-material-calendar.bradb.net/-->
<?php $this->headScript()
	->prependFile('bower_components/flot/jquery.flot.selection.js')
	->prependFile('bower_components/flot/jquery.flot.time.js')
	->prependFile('bower_components/flot/jquery.flot.js'); ?>
<span ng-controller="calendarCtrl" layout="row" layout-sm="column">
	<div flex layout-padding>
		<div flex layout layout-fill>
			<md-content class="layout-fill ng-scope layout-column">
				<md-toolbar>
					<div class="md-toolbar-tools layout-row">
						<div class="flex"></div>
						<h2 class="calendar-md-title"><span><?=$this->translate('Summary')?></span></h2>

						<div class="flex" style="text-align: right">
							<!--								BUTTONS HERE-->

						</div>
					</div>
				</md-toolbar>
				<md-content layout-padding layout="row" class="calendar ng-scope flex"
							style="border: 1px solid rgba(0, 0, 0, 0.117647); min-height: 100px; ">
					<div class="summary_page" style="width:100%;" summary-graph ng-model="summary">
					</div>
					<span class="legend"></span>
				</md-content>
				<md-content layout-padding layout="row" class="calendar ng-scope flex"
							style="border: 1px solid rgba(0, 0, 0, 0.117647); min-height: 100px; max-height: 100px; overflow-y: auto;">
					<div class="md-list-item-text" ng-repeat="s in sum" flex>
						<h3> {{ s.number }} óra</h3>
						<p> {{ s.type }} </p>
					</div>

				</md-content>

			</md-content>
		</div>

		<calendar-md flex="100" layout layout-fill
					 calendar-direction="direction"
					 on-prev-month="prevMonth"
					 on-next-month="nextMonth"
					 on-day-click="dayClick"
					 title-format="'y MMMM'"
					 ng-model='selectedDate'
					 week-starts-on="firstDayOfWeek"
					 day-format="dayFormat"
					 day-content="setDayContent"
					 disable-future-selection="false"
		</calendar-md>


	</div>
	<div flex layout-padding>
		<div flex layout layout-fill>
			<md-content class="layout-fill ng-scope layout-column">
				<md-toolbar>
					<div class="md-toolbar-tools layout-row">
						<div class="flex"></div>
						<h2 class="calendar-md-title"><span>Részletek ({{current_day}})</span></h2>

						<div class="flex" style="text-align: right">
							<md-button ng-click="saveDay()" class="flex save-time-details" aria-label="Mentés">
								<ng-md-icon size="30" style="fill: rgba(255,255,255,0.87);" icon="check"></ng-md-icon>
							</md-button>
						</div>
					</div>
				</md-toolbar>
				<md-content layout-padding layout="row" class="calendar ng-scope flex"
							style="border: 1px solid rgba(0, 0, 0, 0.117647);">
					<time-tracker flex ng-model="dateContent">
						<md-card layout='row' layout-padding flex
								 ng-repeat="value in dateContent track by $index">
							<div layout="column" style="width: 5px; padding: 0;" layout-align="center center"
								 class="day-color-{{value.entryTypeId}}">
								&nbsp;
							</div>

							<div flex layout="column">
								<md-input-container flex>
									<label>Típus</label>
									<md-select ng-model="value.entryTypeId">
										<md-option ng-repeat="dayType in dayTypes" value="{{dayType.entryTypeId}}">
											{{dayType.entryName}}
										</md-option>
									</md-select>
								</md-input-container>
								<md-input-container flex>
									<label>Projekt</label>
									<md-select ng-model="value.project">
										<md-option ng-repeat="project in projects" ng-click="updateTasks(value,project)"
												   value="{{project.projectId}}">
											{{project.projectName}}
										</md-option>
									</md-select>
								</md-input-container>
								<md-input-container flex>
									<label>Feladat</label>
									<md-select ng-model="value.task">
										<md-option ng-repeat="task in value.tasks" value="{{task.taskId}}">
											{{task.taskName}}
										</md-option>
									</md-select>
								</md-input-container>

								<md-input-container flex>
									<label>Megjegyzés</label>
									<textarea ng-model="value.comment"></textarea>
								</md-input-container>
							</div>

							<div flex layout="column">
								<div flex layout="row">
									<span class="md-block">Kezdés</span>
								</div>
								<div flex layout="row">
									<md-input-container class="md-block" flex>
										<label>Óra</label>
										<input type="number" ng-change="" time-handler="hour"
											   ng-model="value.start.hour">
									</md-input-container>
									<md-input-container class="md-block" flex>
										<label>Perc</label>
										<input type="number" time-handler="minute" ng-model="value.start.min">
									</md-input-container>
								</div>
								<div flex layout="row">
									<span class="md-block">Befejezés</span>
								</div>
								<div flex layout="row">
									<md-input-container class="md-block" flex>
										<label>Óra</label>
										<input type="number" time-handler="hour" ng-model="value.end.hour">
									</md-input-container>
									<md-input-container class="md-block" flex>
										<label>Perc</label>
										<input type="number" time-handler="minute" ng-model="value.end.min">
									</md-input-container>
								</div>
								<md-card-actions layout="row" layout-align="end center">
									<md-button class="md-raised md-warn" aria-label="Törlés"
											   ng-click="removeInstance($index)">
										<ng-md-icon icon="delete"
													style="position:relative;top:8px;fill: rgba(255,255,255,0.87);"></ng-md-icon>
									</md-button>

								</md-card-actions>

							</div>
						</md-card>
					</time-tracker>
				</md-content>
			</md-content>
		</div>
	</div>
</span>