<form method="post" action="#" layout="row" layout-sm="column">
<!--    <md-input-container ng-init="selectedyear=2016">-->
<!--        <md-select ng-model="selectedyear">-->
<!--            <md-option ng-value="year" ng-repeat="year in [2015,2016]">{{ year }}</md-option>-->
<!--        </md-select>-->
<!--    </md-input-container>-->
<!--    <md-input-container>-->
<!--        <md-select ng-model="selectedmonth">-->
<!--            <md-option ng-value="month" ng-repeat="month in [1,2,3,4,5,6,7,8,9,10,11,12]">{{ month }}</md-option>-->
<!--        </md-select>-->
<!--    </md-input-container>-->
    <input type="number" value="2016" name="year"><br>
    <input type="number" value="01" name="month"><br>
    <input type="submit" value="save">
</form>